# Configuracion interna UWS (NO publica)
# Recargar con: systemctl reload uws-app
[app]
name      = uws-ucc-app
env       = production
debug     = false

[secrets]
db_user   = ctf_admin
db_pass   = ctf_admin_pass
api_token = uws-prod-7c19-bb44-3e1f-9a02

# Bandera de proximidad para auditoria interna:
#   FLAG{UCC_UWS_Config_Leaked}
